### ISSUE TITLE
AutoMine does not work with GUI opened

### ISSUE THREAD

**Issue by coolnoob78** [Wurst-Imperium/Wurst7#1045] opened 2024-07-30 18:29 UTC
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

In older version, AutoMine worked in the menu, chat, or inventory GUI, it no longer does that

### Repro steps

Activate AutoMine
Open GUI

### Wurst Client version

latest

### Minecraft version

1.20.4

**Comment by Alexander01998** [comment] 2024-07-30 19:19
Hey @coolnoob78.

Thanks for the report, but this has already been fixed in [Wurst 7.44](https://www.wurstclient.net/updates/wurst-7-44/).

Once the 1.20.4 branch gets updated (which I plan to do soon), it will also have this fix.

Closing this issue for now since it's a duplicate of #1029.

**Closed by Alexander01998** 2024-07-30 19:19 UTC
Labels: type:bug, status:unconfirmed
