### ISSUE TITLE
Kicked for fying in singleplayer.

### ISSUE THREAD

**Issue by energy11a** [Wurst-Imperium/Wurst7#622] opened 2022-04-10 10:06 UTC
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?
I get kicked for fying in singleplayer.
## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. enter world
2.  fly
3. profit(you get kicked)

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

(crash report goes here)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by energy11a** [comment] 2022-04-10 10:09
![2022-04-10_13 08 05](https://user-images.githubusercontent.com/46869399/162613229-fc41aa88-317a-4257-9e46-1a7faea9d6e2.png)

**Comment by TheGrandCurator** [comment] 2022-04-10 11:24
Duplicate of #73 See #556 which is the update of #78.

**Comment by JRmodX** [comment] 2022-08-23 13:43
This happens normally in LAN worlds

**Comment by Alexander01998** [comment] 2023-09-11 11:39
Closing this as a Flight kick bypass was added in [Wurst 7.29](https://www.wurstclient.net/updates/wurst-7-29/).

**Closed by Alexander01998** 2023-09-11 11:39 UTC
Labels: type:bug
