### ISSUE TITLE
Wurst Options button sits on top of ModMenu's mods button in the pause menu

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Wurst-Imperium/Wurst7#435] opened 2021-06-28 17:08 UTC
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
Unrelated to #434! #434 occurred recently, where this has been going on for a long time. this also only happens in pause.
The Wurst Options button sits on top of the Mods button in the pause menu.

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Install ModMenu
2. go into a world
3. Pause
4. no mods button

## Screenshots / Videos (Optional)
TODO

**Comment by sudofox** [comment] 2021-09-09 20:55
This seems to be overriding other buttons in the pause menu as well, such as "Send feedback" etc. They become visible again when you disable Wurst through the Statistics menu.

**Comment by sudofox** [comment] 2021-10-14 16:57
This is particularly annoying recently as I can't reconfigure any of my mods in-game - I have to save and close my world each time I want to change any settings unless the particular mod has a menu hotkey.

**Comment by sudofox** [comment] 2021-10-15 20:31
This is how ModMenu handles it: it checks for the bug report button and adds itself after that, modifying the spacing.

https://github.com/TerraformersMC/ModMenu/blob/71c32a758b817af66cb3de491f91bb9b82451f7d/src/main/java/com/terraformersmc/modmenu/event/ModMenuEventHandler.java#L79

Wurst actually removes those two buttons for whatever reason, so Mod Menu button isn't being added at all.

https://github.com/Wurst-Imperium/Wurst7/blob/9abdf8d2518b5cc7a2dc42698ca8c2c792a07dd8/src/main/java/net/wurstclient/mixin/GameMenuScreenMixin.java#L65

**Comment by sudofox** [comment] 2021-10-15 20:52
Here's a temporary fix to get you going for now:

```diff
diff --git a/src/main/java/net/wurstclient/mixin/GameMenuScreenMixin.java b/src/main/java/net/wurstclient/mixin/GameMenuScreenMixin.java
index 9f9a1343..91ae8935 100644
--- a/src/main/java/net/wurstclient/mixin/GameMenuScreenMixin.java
+++ b/src/main/java/net/wurstclient/mixin/GameMenuScreenMixin.java
@@ -48,12 +48,12 @@ public abstract class GameMenuScreenMixin extends Screen
                        return;
                
                addWurstOptionsButton();
-               removeFeedbackAndBugReportButtons();
+               // removeFeedbackAndBugReportButtons();
        }
        
        private void addWurstOptionsButton()
        {
-               wurstOptionsButton = new ButtonWidget(width / 2 - 102, height / 4 + 56,
+               wurstOptionsButton = new ButtonWidget(width / 2 - 102, height / 4 + 126,
                        204, 20, new LiteralText("            Options"),
                        b -> openWurstOptions());
```

It might not look pretty, but it'll allow you access to the ModMenu.

**Comment by KTibow** [comment] 2021-12-25 16:55
Possible duplicate of #291

**Comment by Alexander01998** [comment] 2022-04-26 11:58
Fixed in 9aff6c81bb33ac1555b5930c801aa62a1fac2b42.

**Closed by Alexander01998** 2022-04-26 11:58 UTC
Labels: bug

**Comment by TheAwesome98-Real** [comment] 2022-04-26 12:43
thanks

**Comment by Alexander01998** [comment] 2025-03-27 09:02
Hey @Penchorus,

You can actually adjust this in the ModMenu settings. ModMenu has three different modes you can choose from: Replace, Insert, and Icon.

It looks like you're currently in Replace mode, which places the ModMenu button underneath the Wurst Options button. If you switch to either Insert or Icon mode, that will make the ModMenu button show up next to the Wurst Options button like so:

Insert mode:
![screenshot of Minecraft game menu with Wurst and ModMenu in Insert mode](https://github.com/user-attachments/assets/10ff9ae4-026b-47bb-ae5c-6aa7266f5336)

Icon mode:
![screenshot of Minecraft game menu with Wurst and ModMenu in Icon mode](https://github.com/user-attachments/assets/9dfffd5c-ee3c-43ba-9cfd-a119b7da929e)

Here's how you can change it:
1. Open the ModMenu Options.
2. Look for the "Game Menu" setting.
3. Switch it from "Replace" to either "Insert" or "Icon."

![screenshot of ModMenu Options with a red circle around the Game Menu setting](https://github.com/user-attachments/assets/966d8ab2-f359-4551-a755-49866388ade7)

Hope this helps!
