### ISSUE TITLE
KillAura isn't aware about different reaches in Creative and Survival mode.

### ISSUE THREAD

**Issue by alexander4308** [Wurst-Imperium/Wurst7#1071] opened 2024-10-12 17:08 UTC
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

This is stupid, killaura missing hits because of this.

### Repro steps

1. Enter survival mode in a singleplayer world
2. Enable KillAura or MultiAura
3. Appear in the middle of Creative and Survival reach range.

### Wurst Client version

7.46.1 (dirty)

### Minecraft version

1.21.1

**Comment by Alexander01998** [comment] 2024-10-12 18:36
Hey @alexander4308,

Thanks for reaching out! I understand your concerns about missing hits, but this is actually intended behavior.

Killaura (and MultiAura, etc.) have a "Range" slider in their settings that lets you directly specify how much reach distance they should have, regardless of the gamemode you're in. So if you set the range to a value that only works in Creative mode, then naturally it will only work there.

I fully agree that it would be useful to have some way for the range to automatically adjust itself to the different gamemodes (and gamerules) that you can have on each server, but that would be a suggestion for a complete overhaul of how range sliders work in in Wurst, and that needs a lot of careful consideration to ensure it works well for all users.

Such a system would have to be flexible, adjusting to both gamemode and gamerule based reach and not breaking when either of those values suddenly change. It would have to be easy to use - many users have no idea what the entity interaction gamerule is set to on their server or what that even means, but they must still be able to figure out their Killaura settings. And it would have to be backwards-compatible - if someone wants to keep a static 5m range after the update, they must have a way to do that.

I'm closing this issue since there is no bug here, but I'm keeping the suggestion in mind for future improvements. If you can come up with a set of settings that meets all the above criteria, feel free to open a new issue using the suggestion template.

**Closed by Alexander01998** 2024-10-12 18:36 UTC
Labels: type:bug, status:unconfirmed
